version: '1.0.0.{build}'

init:
- ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:flowVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

assembly_info:
  patch: true
  file: SolutionAssemblyInfo.cs
  assembly_version: $(flowVersion)
  assembly_file_version: $(flowVersion)
  assembly_informational_version: $(flowVersion)
dotnet_csproj:
  patch: true
  file: 'Flow.*\*.csproj'
  version: $(flowVersion)
  package_version: $(flowVersion)
  assembly_version: $(flowVersion)
  file_version: $(flowVersion)
  informational_version: $(flowVersion)

skip_commits:
  files:
    - '*.md'

image: Visual Studio 2019
platform: Any CPU
configuration: Release
before_build:
- ps: nuget restore
build:
  project: Flow.Launcher.sln
  verbosity: minimal

artifacts:
- path: 'Output\Packages\Flow-Launcher-*.zip'
  name: Zip
- path: 'Output\Release\Flow.Launcher.Plugin.*.nupkg'
  name: Plugin nupkg
- path: 'Output\Release\Flow.Launcher.Plugin.*.snupkg'
  name: Plugin snupkg