version: 1.0.{build}

assembly_info:
  patch: true
  file: SolutionAssemblyInfo.cs
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

dotnet_csproj:
  patch: true
  file: 'Flow.*\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

skip_commits:
  files:
    - '*.md'

image: Visual Studio 2019
platform: Any CPU
configuration: Release
before_build:
- ps: nuget restore
build:
  project: Flow.Launcher.sln
  verbosity: minimal

artifacts:
- path: 'Output\Packages\*.exe'
  name: Setup File
- path: 'Output\Packages\*.nupkg'
  name: Squirrel nupkg
- path: 'Output\Packages\RELEASES'
  name: Squirrel RELEASES
- path: 'Output\Packages\Flow-Launcher-*.zip'
  name: Zip
- path: 'Output\Release\Flow.Launcher.Plugin.*.nupkg'
  name: Plugin nupkg
- path: 'Output\Release\Flow.Launcher.Plugin.*.snupkg'
  name: Plugin snupkg