name: "\U0001F41E Bug Report"
description: Create a bug report to help us improve Flow Launcher
title: "BUG: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: >
            I have checked that this issue has not already been reported.

  - type: textarea
    attributes:
      label: Problem Description
      description: A clear and concise description of what the problem is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: >
        1. ...

        2. ...

        3. ...

  - type: textarea
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.

  - type: input
    attributes:
      label: Flow Launcher Version
      description: Go to "Settings" => "About".
    validations:
      required: true

  - type: input
    attributes:
      label: Windows Build Number
      description: Run "ver" at CMD (command prompt) or go to Windows Settings -> Systems -> About.
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Error Log
      description: >
        Log file place:
        
        Go to "Settings" => "About" => "DevTools" => Click Tools Button => "Log Folder".

        - The latest version place: `%AppData%\FlowLauncher\Logs\<version>\<date>.txt`

        - For portable mode: `Your-Flow-Location\<App-Version>\UserData\Logs\<version>\<date>.txt`
      value: >
        <details>


        ```shell


        Replace this line with the important log contents.


        ```

        </details>


        <!-- # Or drag and drop the log file and delete the above detail part. -->
